#!/bin/bash

tput clear;

echo "SPEED CALCULATOR"


#This should be able to ask user for time and distance and then give back how fast the object was...

#printf "\nWaht was the distance? Include units but with a space away from numbers... " &&
#read dist &&
dist="60 m"
distNo=$(echo $dist | cut -d " " -f1)


printf "\nWhat was the time? Include units with a space away from numbes... " &&
read time &&
timeNo=$(echo $time | cut -d " " -f1)

speed=$(echo ${distNo}"/"${timeNo} | bc)
distU=$(echo $dist | cut -d " " -f2)
timeU=$(echo $time | cut -d " " -f2)

printf "\nThis was the speed... ${speed}${distU}/${timeU}"
